language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.0
addons:
  branches:
    - dev
    - master
script:
  - dotnet restore src/LoggingTest
  - dotnet test src/LoggingTest -f netcoreapp3.0
