language: csharp
sudo: required
dist: trusty
dotnet: 1.0.0-preview2-003131
env: DOTNETCORE=1
addons:
  branches:
    - dev
    # - master
before_install:
  - chmod +x build.sh
script:
  - ./build.sh
  